### PR TITLE
Add Ecal Endcaps onnx models and average occupancy files for ECAL MLDQM

### PR DESCRIPTION
**Pull request by abhih1**
This PR adds the onnx models for EE+ and EE- , and 2022 average digi occupancy files for EB, EE- and EE+ for the inference in the autoencoder based online Ecal DQM feature to the dedicated data repository. 
To be used in PR: https://github.com/cms-sw/cmssw/pull/41175

### CODE REVIEW

**Comment by emanueleusai** [comment]
please test

**Comment by emanueleusai** [comment]
type ecal

**Comment by rappoccio** [comment]
+1

**Comment by rappoccio** [comment]
merge

* Signatures are all collected in the cmssw PR so bypassing signatures here.

**Pull request merged**
