### PR TITLE
Add list of problematic Supercrystals in Endcaps for LED Quality plot

### PR DESCRIPTION
**Pull request by abhih1**
This PR adds to the dedicated data repository, the data file containing the list of ix, iy, iz coordinates and the raw detector ID of the Supercrystals in the Ecal Endcaps which are known to be problematic.
This list is used to update the quality cuts on these supercrystals in the LED Quality plots.

### CODE REVIEW

**Comment by jfernan2** [comment]
+1

**Comment by perrotta** [comment]
@abhih1 I think that this list should get merged together with #37378: correct?
And then, it should be also made available to the backports #37404 (12_3_X) and #37380 (12_2_X)

**Comment by abhih1** [comment]
@perrotta Yes, that's right.

**Comment by perrotta** [comment]
+1
- Needed by #37378, just merged in master

**Comment by perrotta** [comment]
ping bot

**Comment by perrotta** [comment]
merge

**Comment by smuzaffar** [comment]
+externals

**Comment by qliphy** [comment]
@smuzaffar  Would you please make a cmsdist PR for 12_2_X and 12_3_X?

**Comment by smuzaffar** [comment]
FYI @qliphy 
12.2.X: https://github.com/cms-sw/cmsdist/pull/7740
12.3.X: https://github.com/cms-sw/cmsdist/pull/7739

**Pull request merged**
